name: Build Docker image
# This workflow is triggered 1st, 16th and 31st
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
jobs:
  build:
    name: latest
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
       #- name: Login to DockerHub Registry
       # run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin   
     - name: Build Docker image
       run: |
        ./compile.sh BOARD="arm-64" ARCH="arm64" BRANCH="current" RELEASE="focal" KERNEL_ONLY="no" KERNEL_CONFIGURE="no" BUILD_MINIMAL="no" BUILD_DESKTOP="no"
        #docker tag armbian:$(cat VERSION) armbian/build:latest
     - name: Push Docker image
       run: docker push armbian/build:latest

